# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ZEgB5rY4f66FPyxBk8FVb7MM
    ports:
        - 32032:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#      - 5432:5432
